name: binnetwork
description: Network Monitoring Apps.
publish_to: 'playstore'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  connectivity_plus: ^4.0.1
  network_info_plus: ^4.0.1
  dart_ping: ^8.0.1
  whois: ^1.0.0
  flutter_traceroute: ^0.0.1+2
  speed_test_dart: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true